#!/usr/bin/env python3
"""Measure empirical (H, M) coordinates for natural corpus files.

H = marginal byte entropy (bits/byte) from the byte frequency histogram.

Two M estimates are reported:
  M_greedy  — fraction of bytes covered by greedy LZ77 matches (min_len=3,
               window=32768).  Fast but overcounts; used for rough comparison.
  M_cost    — fraction of bytes covered by cost-profitable LZ77 matches.
               A match at distance D, length L is "profitable" only if
               log2(D) + log2(L) + 1  <  L * H  (copy cost < literal cost).
               This is comparable to the construction M used in calibrated.py.

Output: build/bench/natural-corpus-hm.csv

Usage:
    python scripts/measure-natural-corpus.py
    python scripts/measure-natural-corpus.py --dirs build/raw/silesia build/raw/logs
"""
from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def byte_entropy(data: bytes) -> float:
    """Shannon entropy of the byte distribution, bits/byte."""
    counts = [0] * 256
    for b in data:
        counts[b] += 1
    n = len(data)
    if n == 0:
        return 0.0
    return -sum((c / n) * math.log2(c / n) for c in counts if c > 0)


def _lz77_parse(data: bytes, min_len: int = 4, window: int = 32768
                ) -> list[tuple[int, int, int]]:
    """Return list of (pos, distance, length) for every accepted match.

    Greedy LZ77: always takes the longest available match ≥ min_len.
    Uses a hash table on min_len-byte keys.
    min_len=4 matches squishy/corpus/metrics.py (LZ_MIN_LEN=4).
    """
    n = len(data)
    pos_table: dict[bytes, int] = {}
    matches: list[tuple[int, int, int]] = []
    pos = 0

    while pos < n:
        if pos + min_len > n:
            pos += 1
            continue

        key = data[pos:pos + min_len]
        prev = pos_table.get(key)

        if prev is not None and pos - prev <= window:
            dist = pos - prev
            match_len = min_len
            max_back = min(pos, window)
            src = prev
            while (pos + match_len < n
                   and match_len < max_back
                   and data[src + match_len] == data[pos + match_len]):
                match_len += 1

            matches.append((pos, dist, match_len))
            for i in range(match_len):
                if pos + i + min_len <= n:
                    pos_table[data[pos + i:pos + i + min_len]] = pos + i
            pos += match_len
        else:
            pos_table[key] = pos
            pos += 1

    return matches


def lz77_match_fraction(data: bytes, min_len: int = 4, window: int = 32768) -> float:
    """Fraction of bytes covered by greedy LZ77 matches (min_len=4, window=32768).

    min_len=4 matches squishy/corpus/metrics.py (LZ_MIN_LEN=4) so results are
    comparable to measure-corpus.py output.
    """
    n = len(data)
    if n < min_len:
        return 0.0
    matches = _lz77_parse(data, min_len, window)
    return sum(length for _, _, length in matches) / n


def lz77_cost_match_fraction(data: bytes, H: float,
                              min_len: int = 4, window: int = 32768) -> float:
    """Fraction of bytes covered by *cost-profitable* LZ77 matches.

    A match at distance D, length L is profitable only when:
        log2(D) + log2(L) + 1  <  L * H
    (copy token cost < encoding the same L bytes as literals at H bits/byte).

    This gives an M estimate comparable to the construction M in calibrated.py,
    where M is the fraction of bytes generated by the copy path.
    """
    n = len(data)
    if n < min_len or H <= 0:
        return 0.0
    matches = _lz77_parse(data, min_len, window)
    copy_bytes = 0
    for _, dist, length in matches:
        if dist < 1:
            continue
        copy_cost = math.log2(dist) + math.log2(length) + 1.0
        literal_cost = length * H
        if copy_cost < literal_cost:
            copy_bytes += length
    return copy_bytes / n


def measure_file(path: Path) -> dict:
    data = path.read_bytes()
    H = byte_entropy(data)
    M_greedy = lz77_match_fraction(data)
    M_cost = lz77_cost_match_fraction(data, H)
    return {
        "corpus":      path.parent.name,
        "filename":    path.name,
        "size_bytes":  len(data),
        "H_marginal":  round(H, 4),
        "M_greedy":    round(M_greedy, 4),
        "M_cost":      round(M_cost, 4),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dirs", nargs="+",
        default=["build/raw/silesia"],
        help="Directories containing natural corpus files",
    )
    parser.add_argument(
        "--out", default="build/bench/natural-corpus-hm.csv",
        help="Output CSV path",
    )
    parser.add_argument(
        "--extensions", default="",
        help="Comma-separated extensions to include (default: all files)",
    )
    args = parser.parse_args()

    exts = set(args.extensions.split(",")) - {""} if args.extensions else None
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    files: list[Path] = []
    for d in args.dirs:
        p = Path(d)
        if not p.exists():
            print(f"  WARN: {p} does not exist, skipping", file=sys.stderr)
            continue
        for f in sorted(p.iterdir()):
            if not f.is_file():
                continue
            if exts and f.suffix not in exts:
                continue
            files.append(f)

    if not files:
        print("No files found.", file=sys.stderr)
        sys.exit(1)

    print(f"Measuring {len(files)} files …")
    rows: list[dict] = []
    for f in files:
        print(f"  {f.parent.name}/{f.name} ({f.stat().st_size:,} bytes) … ", end="", flush=True)
        row = measure_file(f)
        rows.append(row)
        print(f"H={row['H_marginal']:.3f}  M_greedy={row['M_greedy']:.3f}  M_cost={row['M_cost']:.3f}")

    fieldnames = ["corpus", "filename", "size_bytes", "H_marginal", "M_greedy", "M_cost"]
    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\nWrote {len(rows)} rows to {out_path}")
    print("\n── Natural corpus (H, M) coordinates ────────────────────────────────────────────")
    print(f"  {'file':30s}  H(bpb)  M_greedy  M_cost")
    print(f"  {'':30s}  {'':6s}  (overcts)  (vs construction)")
    for row in sorted(rows, key=lambda r: r["H_marginal"]):
        print(f"  {row['filename']:30s}  {row['H_marginal']:6.3f}  {row['M_greedy']:8.3f}  {row['M_cost']:6.3f}")

    print("\n── Synthetic grid coverage (for reference) ──────────────────────────────────────")
    print("  H ∈ {1,2,3,4,5,6,7,8}  M ∈ {0.00, 0.25, 0.50, 0.75}")
    H_vals = [r["H_marginal"] for r in rows]
    M_cost_vals = [r["M_cost"] for r in rows]
    M_greedy_vals = [r["M_greedy"] for r in rows]
    print(f"  Natural H range:        [{min(H_vals):.2f}, {max(H_vals):.2f}]")
    print(f"  Natural M_cost range:   [{min(M_cost_vals):.3f}, {max(M_cost_vals):.3f}]")
    print(f"  Natural M_greedy range: [{min(M_greedy_vals):.3f}, {max(M_greedy_vals):.3f}]  (overcounted)")
    high_M = [r for r in rows if r["M_cost"] > 0.50]
    if high_M:
        print(f"  Files with M_cost > 0.50: {[r['filename'] for r in high_M]}")
    else:
        print("  No natural files with M_cost > 0.50 (synthetic grid goes to 0.75)")


if __name__ == "__main__":
    main()
