"""Generate k-th order Markov chain sources.

Each file is generated by a finite-state Markov chain where:
  - State       = previous k bytes
  - Transitions = SHAKE-256(seed ‖ state) → 256 score bytes → rank permutation
                  → weight_i = exp(−τ × rank_i) → normalised PMF

Corpus axes:
  k (order):  2, 4, 8  (v3 legacy); v4 uses k ∈ {1, 2, 4} via v4_driver
  tau (temp): 0.5, 1.0, 2.0  (lower τ → more peaked → lower entropy)
  sizes:      256K, 4M, 64M  (v3 legacy); v4 uses 4M, 64M, 1G

Key property: because every state's PMF is the same weight vector permuted,
H(P(·|s)) is state-independent → entropy rate = _geometric_rank_entropy(tau).

Seed computation:
  sha256(f"markov:{k}:{tau}:{size}:{rep}")[:8] → data_seed (uint64)
"""
from __future__ import annotations

import hashlib
import json
import math
import random
from collections import OrderedDict
from typing import Any

from squishy.core.config import BuildConfig
from squishy.core.fs import write_bytes_atomic

# ── Corpus axes ────────────────────────────────────────────────────────────────

K_VALUES:   list[int]   = [2, 4, 8]
TAU_VALUES: list[float] = [0.1, 0.5, 1.0]
SIZES: list[tuple[str, int]] = [
    ("256K",  262144),
    ("4M",   4194304),
    ("64M", 67108864),
]
REPLICATES: list[str] = ["s0", "s1", "s2"]

PILOT_STEPS: int = 100_000  # used for R_ref estimation


# ── Seed helpers ───────────────────────────────────────────────────────────────

def _make_seed(tag: str) -> int:
    return int.from_bytes(hashlib.sha256(tag.encode()).digest()[:8], "big")


def _data_seed(k: int, tau: float, size: int, rep: str) -> int:
    return _make_seed(f"markov:{k}:{tau}:{size}:{rep}")


# ── Transition distribution ────────────────────────────────────────────────────

def _transition_pmf(seed: int, state: bytes, tau: float) -> list[float]:
    """Compute P(next_byte | state) via SHAKE-256 geometric-rank kernel.

    Process:
      1. SHAKE-256(seed_bytes ‖ state) → 256 bytes (one independent score per byte value)
      2. Sort the 256 byte indices by score (descending) → rank ordering
      3. Assign weight = exp(-tau × rank) to each byte value
      4. Normalise to a PMF

    SHAKE-256 gives 256 independent score bytes with no tiling artifacts (unlike
    SHA-512 tiled ×4, which produces 64 identical quadruplets and causes rank ties).

    Key property: the weight VECTOR is the same for every state — only the assignment
    of byte values to ranks differs. Therefore H(P(·|s)) is identical across all states,
    and R_ref = _geometric_rank_entropy(tau) exactly (no pilot run needed).

    Calibrated R_ref vs tau:
      tau = 0.1: R_ref ≈ 4.8 bpb
      tau = 0.5: R_ref ≈ 2.5 bpb
      tau = 1.0: R_ref ≈ 1.5 bpb

    Convention: HIGHER tau → LOWER entropy (more deterministic).
    """
    h = hashlib.shake_256(seed.to_bytes(8, "big") + state).digest(256)
    ranked = sorted(range(256), key=lambda i: h[i], reverse=True)
    weights: list[float] = [0.0] * 256
    for rank, byte_idx in enumerate(ranked):
        weights[byte_idx] = math.exp(-tau * rank)
    Z = sum(weights)
    return [w / Z for w in weights]


def _geometric_rank_entropy(tau: float, K: int = 256) -> float:
    """Exact entropy of the geometric-rank PMF for K byte values.

    The weight vector is (exp(-tau×0), exp(-tau×1), ..., exp(-tau×(K-1))), normalized.
    Since all states share this vector (permuted), this equals the Markov entropy rate.
    """
    weights = [math.exp(-tau * r) for r in range(K)]
    Z = sum(weights)
    return -sum((w / Z) * math.log2(w / Z) for w in weights if w > 0)



# ── Efficient cached stream generator ─────────────────────────────────────────

class MarkovGenerator:
    """Streaming k-th order Markov generator with LRU transition cache."""

    def __init__(self, k: int, tau: float, seed: int) -> None:
        self.k = k
        self.tau = tau
        self.seed = seed
        self._cache: OrderedDict[bytes, list[float]] = OrderedDict()
        self._rng = random.Random(seed)
        self._state = bytes([0] * k)

    def _pmf(self, state: bytes) -> list[float]:
        if state not in self._cache:
            if len(self._cache) >= 65536:
                # LRU eviction: remove oldest entry (OrderedDict insertion order)
                self._cache.pop(next(iter(self._cache)))
            self._cache[state] = _transition_pmf(self.seed, state, self.tau)
        else:
            # Move to end (most-recently-used)
            self._cache[state] = self._cache.pop(state)
        return self._cache[state]

    def next_byte(self) -> int:
        pmf = self._pmf(self._state)
        b = self._rng.choices(range(256), weights=pmf)[0]
        self._state = self._state[1:] + bytes([b])
        return b

    def generate(self, size: int) -> bytes:
        return bytes(self.next_byte() for _ in range(size))


# ── R_ref (exact closed form) ──────────────────────────────────────────────────

def estimate_rref(k: int, tau: float, seed: int,
                  pilot_steps: int = PILOT_STEPS) -> tuple[float, float]:
    """R_ref for the geometric-rank Markov chain (exact closed form).

    Because all states share the same conditional entropy — the PMF is a permuted
    copy of the geometric vector (exp(-tau×0), ..., exp(-tau×255)) — the Markov
    entropy rate equals the per-state conditional entropy exactly:

        R_ref = H(exp(-tau × rank) distribution over 256 byte values)

    This is state-independent, so no pilot run is needed. The `k`, `seed`, and
    `pilot_steps` parameters are accepted for API compatibility but are unused.
    Returns (R_ref, 0.0); stderr is 0.0 because the value is exact.
    """
    return _geometric_rank_entropy(tau), 0.0


# ── File generation ────────────────────────────────────────────────────────────

def generate_file(k: int, tau: float, size: int, rep: str) -> bytes:
    seed = _data_seed(k, tau, size, rep)
    gen = MarkovGenerator(k, tau, seed)
    return gen.generate(size)


def ground_truth_record(size_label: str, size: int, k: int, tau: float,
                         rep: str, fname: str) -> dict:
    seed = _data_seed(k, tau, size, rep)
    R_ref, R_ref_stderr = estimate_rref(k, tau, seed)
    return {
        "filename":      fname,
        "size_bytes":    size,
        "k":             k,
        "tau":           tau,
        "R_ref":         round(R_ref, 4),
        "R_ref_stderr":  round(R_ref_stderr, 4),
        "reference_bytes": math.ceil(R_ref * size / 8),
        "generator":     "markov_v1",
        "data_seed":     seed,
    }


# ── Main entry point ───────────────────────────────────────────────────────────

def run(cfg: BuildConfig) -> int:
    """Generate the full Markov source grid. Returns 0 on success, 1 on failure."""
    try:
        out = cfg.raw_dir / "markov"
        out.mkdir(parents=True, exist_ok=True)

        records: list[dict] = []

        for size_label, size in SIZES:
            for k in K_VALUES:
                for tau in TAU_VALUES:
                    for rep in REPLICATES:
                        tau_str = f"tau{tau:.1f}".replace(".", "p")
                        fname = f"{size_label}-k{k}-{tau_str}-{rep}.bin"
                        path = out / fname
                        rec = ground_truth_record(size_label, size, k, tau, rep, fname)
                        records.append(rec)
                        if path.exists():
                            print(f"  skip {fname} (exists)")
                            continue
                        data = generate_file(k, tau, size, rep)
                        write_bytes_atomic(path, data)
                        print(f"  {fname} ({len(data):,} bytes)")

        gt_path = out / "ground-truth.json"
        write_bytes_atomic(gt_path, json.dumps(records, indent=2).encode())
        print(f"  markov: {len(records)} records written to {out}")
        return 0

    except Exception as exc:
        import traceback
        print(f"  ERROR in markov: {exc}")
        traceback.print_exc()
        return 1
