"""Tool detection and version pinning.

Discovers compression tools on PATH, records their versions into tools.lock,
and provides helpers for getting tool paths and versions at build time.

The tools.lock file is the ground truth for which binary produced which output.
When a tool version changes, the content-addressed cache will naturally force
a rebuild of any artifact whose cache key includes that version.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from squishy.core.config import BuildConfig
from squishy.core.fs import write_text_atomic

# Canonical tool names checked by `doctor`.
REQUIRED_TOOLS = ["gzip", "bzip2", "xz", "zstd", "lz4"]
OPTIONAL_TOOLS = ["brotli", "lzma", "lzip", "lzop", "zpaq", "7z", "7zz", "zip",
                  "cpio", "ar", "mksquashfs", "compress", "python3", "curl", "aws"]


def find(name: str) -> str | None:
    """Return the full path to *name* on PATH, or None."""
    return shutil.which(name)


def version(binary: str) -> str:
    """Return the first line of ``binary --version``, or '?' on failure."""
    try:
        r = subprocess.run(
            [binary, "--version"],
            capture_output=True, text=True, timeout=5,
        )
        return ((r.stdout or r.stderr).splitlines() or ["?"])[0].strip()[:120]
    except Exception:
        return "?"


def discover() -> dict[str, str]:
    """Return {tool_name: full_path} for every tool found on PATH."""
    found: dict[str, str] = {}
    for name in REQUIRED_TOOLS + OPTIONAL_TOOLS:
        path = find(name)
        if path:
            found[name] = path
    # Prefer 7zz over 7z when both are present (newer p7zip naming)
    if "7zz" in found and "7z" not in found:
        found["7z"] = found["7zz"]
    return found


def run_doctor(cfg: BuildConfig) -> int:
    """Check toolchain, write tools.lock, print a summary."""
    cfg.build_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "# squishy/tools.lock — tool versions used to produce this corpus",
        f"# generated by: python -m squishy doctor",
    ]

    missing_required: list[str] = []
    missing_optional: list[str] = []

    for name in REQUIRED_TOOLS + OPTIONAL_TOOLS:
        path = find(name)
        if path:
            ver = version(path)
            lines.append(f"{name:<14} {path}  {ver}")
        else:
            lines.append(f"{name:<14} MISSING")
            if name in REQUIRED_TOOLS:
                missing_required.append(name)
            else:
                missing_optional.append(name)

    lock_text = "\n".join(lines) + "\n"
    lock_path = cfg.build_dir / "tools.lock"
    write_text_atomic(lock_path, lock_text)
    print(f"wrote {lock_path}")

    if missing_required:
        print(f"ERROR: required tools missing: {', '.join(missing_required)}")
        return 1
    if missing_optional:
        print(f"NOTE:  optional tools missing (some artifacts will be skipped): "
              f"{', '.join(missing_optional)}")

    hints = {
        "brotli":     "brew install brotli",
        "zpaq":       "brew install zpaq",
        "lzip":       "brew install lzip",
        "lzop":       "brew install lzop",
        "mksquashfs": "brew install squashfs",
        "7z":         "brew install sevenzip",
        "7zz":        "brew install sevenzip",
    }
    for name in missing_optional:
        if name in hints:
            print(f"  hint: {hints[name]}")

    return 0
